### ISSUE TITLE
error: unpack requires a string argument of length 13

### ISSUE THREAD

**Issue by zhausong** [jangaraj/zabbix-agent-stress-test#1]
```
[root@localhost zbx243]# python zabbix-agent-stress-test.py  -s 10.0.1.112 -k "system.uname"
Starting 1 threads, host: 10.0.1.112:10050, key: system.uname
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "zabbix-agent-stress-test.py", line 89, in worker
    zabbixconntest()
  File "zabbix-agent-stress-test.py", line 78, in zabbixconntest
    packed2str(data)
  File "zabbix-agent-stress-test.py", line 47, in packed2str
    header, version, length = struct.unpack('<4sBQ', packed_data[:13])
error: unpack requires a string argument of length 13

Success: 0  Errors: 0   Avg rate: 0.00 qps  Execution time: 1.00 sec
Success: 0  Errors: 0   Avg rate: 0.00 qps  Execution time: 2.00 sec
```

**Comment by jangaraj** [comment]
How did you configure zabbix agent on 10.0.1.112? Is zabbix connection from your test server allowed (setting `Server`)?
