### ISSUE TITLE
error: unpack requires a string argument of length 13

### ISSUE THREAD

**Issue by darrynv** [jangaraj/zabbix-agent-stress-test#2]
./zabbix-agent-stress-test.py -s 127.0.0.1 -k "system.run[sleep 1]" -t 2
Starting 2 threads, host: 127.0.0.1:10050, key: system.run[sleep 1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./zabbix-agent-stress-test.py", line 89, in worker
    zabbixconntest()
  File "./zabbix-agent-stress-test.py", line 78, in zabbixconntest
    packed2str(data)
  File "./zabbix-agent-stress-test.py", line 47, in packed2str
    header, version, length = struct.unpack('<4sBQ', packed_data[:13])
error: unpack requires a string argument of length 13

**UPDATE**
Update your documentation to specify that the agent allow access from localhost in the zabbix_agentd.conf

**Comment by jangaraj** [comment]
That's only about agent configuration. `localhost` is not mandatory and user can use also proper public/private IP/hostname/..., so I don't think that README needs update.
